version: '3.5'
services:
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rails-cms_development
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: src
    depends_on: 
      - db
    ports:
      - "3000:3000"

volumes:
  db-data: