default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: rails-cms_development

test:
  <<: *default
  database: rails-cms_test

production:
  <<: *default
  database: rails-cms-mysql_production
  username: rails-cms-mysql
  password: <%= ENV['DATABASE_PASSWORD'] %>

